# Generated by Django 5.2.3 on 2025-07-11 16:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='phon',
            new_name='phone',
        ),
    ]
