# Generated by Django 5.2.3 on 2025-07-17 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_book'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='category',
            field=models.CharField(choices=[('math', 'Math'), ('technology', 'Technology'), ('bacci', 'Bacci'), ('lean_ai', 'Learn AI')], default='math', max_length=20),
        ),
    ]
