# Generated by Django 5.2.3 on 2025-07-18 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_book_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='category',
            field=models.CharField(choices=[('math', 'Math'), ('technology', 'Technology'), ('bacci', 'Bacci'), ('learn_ai', 'Learn AI')], default='math', max_length=20),
        ),
    ]
